baseURL = 'https://clockwork-critter.github.io/Critter-Corner/'
languageCode = 'en-us'
title = 'Critter Corner'
copyright = 'This work is licensed under CC BY-SA 4.0'
[[module.imports]]
path = "github.com/willfaught/paige"
[params.paige.site]
disable_breadcrumbs = true