baseURL = 'https://clockwork-critter.github.io/Critter-Corner/'
languageCode = 'en-us'
title = 'Critter Corner'
theme = 'PaperMod'
copyright = 'This work is licensed under CC BY-SA 4.0'


[params]
  mainSections = ['friends']
  Description = "The personal website of Clockwork Critter. Contains a blog, a compendium of resources and other projects"
  env = "production"


[[params.socialIcons]]
name = "github"
url = "https://github.com/Clockwork-Critter"


[[params.socialIcons]]
name = "matrix"
url = "https://matrix.to/#/@clockwork_critter:matrix.org"

[[params.socialIcons]]
name = "email"
url = "mailto:clockwork-critter.cassette539@silomails.com"

[[menu.main]]
identifier = "Blog"
name = "Blog"
url = "/blog/"
weight = 10

[[menu.main]]
identifier = "Resources"
name = "Resources"
url = "/resources/"
weight = 20

[[menu.main]]
identifier = "Worldbeast"
name = "Worldbeast"
url = "/worldbeast pages/"
weight = 30